# Header-only
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cpsusie/cjm-numerics
    REF v0.9.0.0-beta
    SHA512 bf7ee8037679a8fce6b88f83460fdfefd76aefba03c90681b7248855c43b08c0460e0b599eae3b4fd5d84ffb0d0f8d12664f998ad3e9a413ca0bc2b7013d122f
    HEAD_REF issue_71
)
set(CMAKE_CXX_STANDARD 20)
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/src/
    PREFER_NINJA
)
file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/include/)
file(INSTALL ${SOURCE_PATH}/src/include/ DESTINATION ${CURRENT_PACKAGES_DIR}/include/)
file(INSTALL ${SOURCE_PATH}/src/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(INSTALL ${SOURCE_PATH}/src/NOTICES.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
file(INSTALL ${SOURCE_PATH}/src/NOTICES.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
file(INSTALL ${SOURCE_PATH}/README.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})



